// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(qidao_coreFFI)
import qidao_coreFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_qidao_core_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_qidao_core_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureQidaoCoreInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
// Initial value and increment amount for handles. 
// These ensure that SWIFT handles always have the lowest bit set
fileprivate let UNIFFI_HANDLEMAP_INITIAL: UInt64 = 1
fileprivate let UNIFFI_HANDLEMAP_DELTA: UInt64 = 2

fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = UNIFFI_HANDLEMAP_INITIAL

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            return doInsert(obj)
        }
    }

    // Low-level insert function, this assumes `lock` is held.
    private func doInsert(_ obj: T) -> UInt64 {
        let handle = currentHandle
        currentHandle += UNIFFI_HANDLEMAP_DELTA
        map[handle] = obj
        return handle
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

     func clone(handle: UInt64) throws -> UInt64 {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return doInsert(obj)
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterDouble: FfiConverterPrimitive {
    typealias FfiType = Double
    typealias SwiftType = Double

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Double {
        return try lift(readDouble(&buf))
    }

    public static func write(_ value: Double, into buf: inout [UInt8]) {
        writeDouble(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}




public protocol AnalysisEngineProtocol: AnyObject, Sendable {
    
    func addInternalLog(msg: String) async 
    
    func analyze(queryJson: String) async throws 
    
    func getLogs() async  -> [String]
    
    func getNextResult() async throws  -> AnalysisResult
    
    func setLoggingEnabled(enabled: Bool) async 
    
    func start(executable: String, args: [String]) async throws 
    
    func stop() async throws 
    
    func terminate(id: String) async throws 
    
    func terminateAll() async throws 
    
}
open class AnalysisEngine: AnalysisEngineProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_qidao_core_fn_clone_analysisengine(self.handle, $0) }
    }
public convenience init() {
    let handle =
        try! rustCall() {
    uniffi_qidao_core_fn_constructor_analysisengine_new($0
    )
}
    self.init(unsafeFromHandle: handle)
}

    deinit {
        try! rustCall { uniffi_qidao_core_fn_free_analysisengine(handle, $0) }
    }

    

    
open func addInternalLog(msg: String)async   {
    return
        try!  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_qidao_core_fn_method_analysisengine_add_internal_log(
                    self.uniffiCloneHandle(),
                    FfiConverterString.lower(msg)
                )
            },
            pollFunc: ffi_qidao_core_rust_future_poll_void,
            completeFunc: ffi_qidao_core_rust_future_complete_void,
            freeFunc: ffi_qidao_core_rust_future_free_void,
            liftFunc: { $0 },
            errorHandler: nil
            
        )
}
    
open func analyze(queryJson: String)async throws   {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_qidao_core_fn_method_analysisengine_analyze(
                    self.uniffiCloneHandle(),
                    FfiConverterString.lower(queryJson)
                )
            },
            pollFunc: ffi_qidao_core_rust_future_poll_void,
            completeFunc: ffi_qidao_core_rust_future_complete_void,
            freeFunc: ffi_qidao_core_rust_future_free_void,
            liftFunc: { $0 },
            errorHandler: FfiConverterTypeSgfError_lift
        )
}
    
open func getLogs()async  -> [String]  {
    return
        try!  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_qidao_core_fn_method_analysisengine_get_logs(
                    self.uniffiCloneHandle()
                    
                )
            },
            pollFunc: ffi_qidao_core_rust_future_poll_rust_buffer,
            completeFunc: ffi_qidao_core_rust_future_complete_rust_buffer,
            freeFunc: ffi_qidao_core_rust_future_free_rust_buffer,
            liftFunc: FfiConverterSequenceString.lift,
            errorHandler: nil
            
        )
}
    
open func getNextResult()async throws  -> AnalysisResult  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_qidao_core_fn_method_analysisengine_get_next_result(
                    self.uniffiCloneHandle()
                    
                )
            },
            pollFunc: ffi_qidao_core_rust_future_poll_rust_buffer,
            completeFunc: ffi_qidao_core_rust_future_complete_rust_buffer,
            freeFunc: ffi_qidao_core_rust_future_free_rust_buffer,
            liftFunc: FfiConverterTypeAnalysisResult_lift,
            errorHandler: FfiConverterTypeSgfError_lift
        )
}
    
open func setLoggingEnabled(enabled: Bool)async   {
    return
        try!  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_qidao_core_fn_method_analysisengine_set_logging_enabled(
                    self.uniffiCloneHandle(),
                    FfiConverterBool.lower(enabled)
                )
            },
            pollFunc: ffi_qidao_core_rust_future_poll_void,
            completeFunc: ffi_qidao_core_rust_future_complete_void,
            freeFunc: ffi_qidao_core_rust_future_free_void,
            liftFunc: { $0 },
            errorHandler: nil
            
        )
}
    
open func start(executable: String, args: [String])async throws   {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_qidao_core_fn_method_analysisengine_start(
                    self.uniffiCloneHandle(),
                    FfiConverterString.lower(executable),FfiConverterSequenceString.lower(args)
                )
            },
            pollFunc: ffi_qidao_core_rust_future_poll_void,
            completeFunc: ffi_qidao_core_rust_future_complete_void,
            freeFunc: ffi_qidao_core_rust_future_free_void,
            liftFunc: { $0 },
            errorHandler: FfiConverterTypeSgfError_lift
        )
}
    
open func stop()async throws   {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_qidao_core_fn_method_analysisengine_stop(
                    self.uniffiCloneHandle()
                    
                )
            },
            pollFunc: ffi_qidao_core_rust_future_poll_void,
            completeFunc: ffi_qidao_core_rust_future_complete_void,
            freeFunc: ffi_qidao_core_rust_future_free_void,
            liftFunc: { $0 },
            errorHandler: FfiConverterTypeSgfError_lift
        )
}
    
open func terminate(id: String)async throws   {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_qidao_core_fn_method_analysisengine_terminate(
                    self.uniffiCloneHandle(),
                    FfiConverterString.lower(id)
                )
            },
            pollFunc: ffi_qidao_core_rust_future_poll_void,
            completeFunc: ffi_qidao_core_rust_future_complete_void,
            freeFunc: ffi_qidao_core_rust_future_free_void,
            liftFunc: { $0 },
            errorHandler: FfiConverterTypeSgfError_lift
        )
}
    
open func terminateAll()async throws   {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_qidao_core_fn_method_analysisengine_terminate_all(
                    self.uniffiCloneHandle()
                    
                )
            },
            pollFunc: ffi_qidao_core_rust_future_poll_void,
            completeFunc: ffi_qidao_core_rust_future_complete_void,
            freeFunc: ffi_qidao_core_rust_future_free_void,
            liftFunc: { $0 },
            errorHandler: FfiConverterTypeSgfError_lift
        )
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeAnalysisEngine: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = AnalysisEngine

    public static func lift(_ handle: UInt64) throws -> AnalysisEngine {
        return AnalysisEngine(unsafeFromHandle: handle)
    }

    public static func lower(_ value: AnalysisEngine) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> AnalysisEngine {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: AnalysisEngine, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAnalysisEngine_lift(_ handle: UInt64) throws -> AnalysisEngine {
    return try FfiConverterTypeAnalysisEngine.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAnalysisEngine_lower(_ value: AnalysisEngine) -> UInt64 {
    return FfiConverterTypeAnalysisEngine.lower(value)
}






public protocol BoardProtocol: AnyObject, Sendable {
    
    func getSize()  -> UInt32
    
    func getStone(x: UInt32, y: UInt32)  -> StoneColor?
    
    /**
     * Attempts to place a stone. Returns true if successful.
     */
    func placeStone(x: UInt32, y: UInt32, color: StoneColor) throws  -> Board
    
    /**
     * Forcefully places a stone without checking rules (for setup stones).
     */
    func withStone(x: UInt32, y: UInt32, color: StoneColor?)  -> Board
    
}
open class Board: BoardProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_qidao_core_fn_clone_board(self.handle, $0) }
    }
public convenience init(size: UInt32) {
    let handle =
        try! rustCall() {
    uniffi_qidao_core_fn_constructor_board_new(
        FfiConverterUInt32.lower(size),$0
    )
}
    self.init(unsafeFromHandle: handle)
}

    deinit {
        try! rustCall { uniffi_qidao_core_fn_free_board(handle, $0) }
    }

    

    
open func getSize() -> UInt32  {
    return try!  FfiConverterUInt32.lift(try! rustCall() {
    uniffi_qidao_core_fn_method_board_get_size(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func getStone(x: UInt32, y: UInt32) -> StoneColor?  {
    return try!  FfiConverterOptionTypeStoneColor.lift(try! rustCall() {
    uniffi_qidao_core_fn_method_board_get_stone(
            self.uniffiCloneHandle(),
        FfiConverterUInt32.lower(x),
        FfiConverterUInt32.lower(y),$0
    )
})
}
    
    /**
     * Attempts to place a stone. Returns true if successful.
     */
open func placeStone(x: UInt32, y: UInt32, color: StoneColor)throws  -> Board  {
    return try  FfiConverterTypeBoard_lift(try rustCallWithError(FfiConverterTypeSgfError_lift) {
    uniffi_qidao_core_fn_method_board_place_stone(
            self.uniffiCloneHandle(),
        FfiConverterUInt32.lower(x),
        FfiConverterUInt32.lower(y),
        FfiConverterTypeStoneColor_lower(color),$0
    )
})
}
    
    /**
     * Forcefully places a stone without checking rules (for setup stones).
     */
open func withStone(x: UInt32, y: UInt32, color: StoneColor?) -> Board  {
    return try!  FfiConverterTypeBoard_lift(try! rustCall() {
    uniffi_qidao_core_fn_method_board_with_stone(
            self.uniffiCloneHandle(),
        FfiConverterUInt32.lower(x),
        FfiConverterUInt32.lower(y),
        FfiConverterOptionTypeStoneColor.lower(color),$0
    )
})
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeBoard: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = Board

    public static func lift(_ handle: UInt64) throws -> Board {
        return Board(unsafeFromHandle: handle)
    }

    public static func lower(_ value: Board) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Board {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: Board, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeBoard_lift(_ handle: UInt64) throws -> Board {
    return try FfiConverterTypeBoard.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeBoard_lower(_ value: Board) -> UInt64 {
    return FfiConverterTypeBoard.lower(value)
}






public protocol GameProtocol: AnyObject, Sendable {
    
    func canGoBack()  -> Bool
    
    func canGoForward()  -> Bool
    
    func getAnalysisMoves()  -> [[String]]
    
    func getBoard()  -> Board
    
    func getCurrentBoardStones()  -> [[String]]
    
    func getCurrentNode()  -> SgfNode
    
    func getCurrentPathMoves()  -> [SgfProperty]
    
    func getCurrentVariationIndex()  -> UInt32
    
    func getInitialStones()  -> [[String]]
    
    func getLastMove()  -> SgfProperty?
    
    func getMainLineMoves()  -> [[String]]
    
    func getMaxMoveCount()  -> UInt32
    
    func getMetadata()  -> GameMetadata
    
    func getMoveCount()  -> UInt32
    
    func getNextColor()  -> StoneColor
    
    func getRootNode()  -> SgfNode
    
    func getVariationCount()  -> UInt32
    
    func goBack()  -> Bool
    
    func goForward(index: UInt32)  -> Bool
    
    func jumpToMoveNumber(target: UInt32) 
    
    func jumpToNode(target: SgfNode) 
    
    func placeStone(x: UInt32, y: UInt32, color: StoneColor) throws 
    
    func setMetadata(metadata: GameMetadata) 
    
    func toSgf()  -> String
    
}
open class Game: GameProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_qidao_core_fn_clone_game(self.handle, $0) }
    }
public convenience init(size: UInt32) {
    let handle =
        try! rustCall() {
    uniffi_qidao_core_fn_constructor_game_new(
        FfiConverterUInt32.lower(size),$0
    )
}
    self.init(unsafeFromHandle: handle)
}

    deinit {
        try! rustCall { uniffi_qidao_core_fn_free_game(handle, $0) }
    }

    
public static func fromSgf(sgfContent: String)throws  -> Game  {
    return try  FfiConverterTypeGame_lift(try rustCallWithError(FfiConverterTypeSgfError_lift) {
    uniffi_qidao_core_fn_constructor_game_from_sgf(
        FfiConverterString.lower(sgfContent),$0
    )
})
}
    

    
open func canGoBack() -> Bool  {
    return try!  FfiConverterBool.lift(try! rustCall() {
    uniffi_qidao_core_fn_method_game_can_go_back(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func canGoForward() -> Bool  {
    return try!  FfiConverterBool.lift(try! rustCall() {
    uniffi_qidao_core_fn_method_game_can_go_forward(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func getAnalysisMoves() -> [[String]]  {
    return try!  FfiConverterSequenceSequenceString.lift(try! rustCall() {
    uniffi_qidao_core_fn_method_game_get_analysis_moves(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func getBoard() -> Board  {
    return try!  FfiConverterTypeBoard_lift(try! rustCall() {
    uniffi_qidao_core_fn_method_game_get_board(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func getCurrentBoardStones() -> [[String]]  {
    return try!  FfiConverterSequenceSequenceString.lift(try! rustCall() {
    uniffi_qidao_core_fn_method_game_get_current_board_stones(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func getCurrentNode() -> SgfNode  {
    return try!  FfiConverterTypeSgfNode_lift(try! rustCall() {
    uniffi_qidao_core_fn_method_game_get_current_node(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func getCurrentPathMoves() -> [SgfProperty]  {
    return try!  FfiConverterSequenceTypeSgfProperty.lift(try! rustCall() {
    uniffi_qidao_core_fn_method_game_get_current_path_moves(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func getCurrentVariationIndex() -> UInt32  {
    return try!  FfiConverterUInt32.lift(try! rustCall() {
    uniffi_qidao_core_fn_method_game_get_current_variation_index(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func getInitialStones() -> [[String]]  {
    return try!  FfiConverterSequenceSequenceString.lift(try! rustCall() {
    uniffi_qidao_core_fn_method_game_get_initial_stones(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func getLastMove() -> SgfProperty?  {
    return try!  FfiConverterOptionTypeSgfProperty.lift(try! rustCall() {
    uniffi_qidao_core_fn_method_game_get_last_move(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func getMainLineMoves() -> [[String]]  {
    return try!  FfiConverterSequenceSequenceString.lift(try! rustCall() {
    uniffi_qidao_core_fn_method_game_get_main_line_moves(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func getMaxMoveCount() -> UInt32  {
    return try!  FfiConverterUInt32.lift(try! rustCall() {
    uniffi_qidao_core_fn_method_game_get_max_move_count(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func getMetadata() -> GameMetadata  {
    return try!  FfiConverterTypeGameMetadata_lift(try! rustCall() {
    uniffi_qidao_core_fn_method_game_get_metadata(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func getMoveCount() -> UInt32  {
    return try!  FfiConverterUInt32.lift(try! rustCall() {
    uniffi_qidao_core_fn_method_game_get_move_count(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func getNextColor() -> StoneColor  {
    return try!  FfiConverterTypeStoneColor_lift(try! rustCall() {
    uniffi_qidao_core_fn_method_game_get_next_color(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func getRootNode() -> SgfNode  {
    return try!  FfiConverterTypeSgfNode_lift(try! rustCall() {
    uniffi_qidao_core_fn_method_game_get_root_node(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func getVariationCount() -> UInt32  {
    return try!  FfiConverterUInt32.lift(try! rustCall() {
    uniffi_qidao_core_fn_method_game_get_variation_count(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func goBack() -> Bool  {
    return try!  FfiConverterBool.lift(try! rustCall() {
    uniffi_qidao_core_fn_method_game_go_back(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func goForward(index: UInt32) -> Bool  {
    return try!  FfiConverterBool.lift(try! rustCall() {
    uniffi_qidao_core_fn_method_game_go_forward(
            self.uniffiCloneHandle(),
        FfiConverterUInt32.lower(index),$0
    )
})
}
    
open func jumpToMoveNumber(target: UInt32)  {try! rustCall() {
    uniffi_qidao_core_fn_method_game_jump_to_move_number(
            self.uniffiCloneHandle(),
        FfiConverterUInt32.lower(target),$0
    )
}
}
    
open func jumpToNode(target: SgfNode)  {try! rustCall() {
    uniffi_qidao_core_fn_method_game_jump_to_node(
            self.uniffiCloneHandle(),
        FfiConverterTypeSgfNode_lower(target),$0
    )
}
}
    
open func placeStone(x: UInt32, y: UInt32, color: StoneColor)throws   {try rustCallWithError(FfiConverterTypeSgfError_lift) {
    uniffi_qidao_core_fn_method_game_place_stone(
            self.uniffiCloneHandle(),
        FfiConverterUInt32.lower(x),
        FfiConverterUInt32.lower(y),
        FfiConverterTypeStoneColor_lower(color),$0
    )
}
}
    
open func setMetadata(metadata: GameMetadata)  {try! rustCall() {
    uniffi_qidao_core_fn_method_game_set_metadata(
            self.uniffiCloneHandle(),
        FfiConverterTypeGameMetadata_lower(metadata),$0
    )
}
}
    
open func toSgf() -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_qidao_core_fn_method_game_to_sgf(
            self.uniffiCloneHandle(),$0
    )
})
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeGame: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = Game

    public static func lift(_ handle: UInt64) throws -> Game {
        return Game(unsafeFromHandle: handle)
    }

    public static func lower(_ value: Game) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Game {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: Game, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeGame_lift(_ handle: UInt64) throws -> Game {
    return try FfiConverterTypeGame.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeGame_lower(_ value: Game) -> UInt64 {
    return FfiConverterTypeGame.lower(value)
}






public protocol GtpEngineProtocol: AnyObject, Sendable {
    
    func sendCommand(cmd: String) async throws  -> String
    
    func start(executable: String, args: [String]) async throws 
    
    func stop() async throws 
    
}
open class GtpEngine: GtpEngineProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_qidao_core_fn_clone_gtpengine(self.handle, $0) }
    }
public convenience init() {
    let handle =
        try! rustCall() {
    uniffi_qidao_core_fn_constructor_gtpengine_new($0
    )
}
    self.init(unsafeFromHandle: handle)
}

    deinit {
        try! rustCall { uniffi_qidao_core_fn_free_gtpengine(handle, $0) }
    }

    

    
open func sendCommand(cmd: String)async throws  -> String  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_qidao_core_fn_method_gtpengine_send_command(
                    self.uniffiCloneHandle(),
                    FfiConverterString.lower(cmd)
                )
            },
            pollFunc: ffi_qidao_core_rust_future_poll_rust_buffer,
            completeFunc: ffi_qidao_core_rust_future_complete_rust_buffer,
            freeFunc: ffi_qidao_core_rust_future_free_rust_buffer,
            liftFunc: FfiConverterString.lift,
            errorHandler: FfiConverterTypeSgfError_lift
        )
}
    
open func start(executable: String, args: [String])async throws   {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_qidao_core_fn_method_gtpengine_start(
                    self.uniffiCloneHandle(),
                    FfiConverterString.lower(executable),FfiConverterSequenceString.lower(args)
                )
            },
            pollFunc: ffi_qidao_core_rust_future_poll_void,
            completeFunc: ffi_qidao_core_rust_future_complete_void,
            freeFunc: ffi_qidao_core_rust_future_free_void,
            liftFunc: { $0 },
            errorHandler: FfiConverterTypeSgfError_lift
        )
}
    
open func stop()async throws   {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_qidao_core_fn_method_gtpengine_stop(
                    self.uniffiCloneHandle()
                    
                )
            },
            pollFunc: ffi_qidao_core_rust_future_poll_void,
            completeFunc: ffi_qidao_core_rust_future_complete_void,
            freeFunc: ffi_qidao_core_rust_future_free_void,
            liftFunc: { $0 },
            errorHandler: FfiConverterTypeSgfError_lift
        )
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeGtpEngine: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = GtpEngine

    public static func lift(_ handle: UInt64) throws -> GtpEngine {
        return GtpEngine(unsafeFromHandle: handle)
    }

    public static func lower(_ value: GtpEngine) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> GtpEngine {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: GtpEngine, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeGtpEngine_lift(_ handle: UInt64) throws -> GtpEngine {
    return try FfiConverterTypeGtpEngine.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeGtpEngine_lower(_ value: GtpEngine) -> UInt64 {
    return FfiConverterTypeGtpEngine.lower(value)
}






public protocol SgfNodeProtocol: AnyObject, Sendable {
    
    func getChildren()  -> [SgfNode]
    
    func getId()  -> String
    
    func getProperties()  -> [SgfProperty]
    
}
open class SgfNode: SgfNodeProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_qidao_core_fn_clone_sgfnode(self.handle, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        try! rustCall { uniffi_qidao_core_fn_free_sgfnode(handle, $0) }
    }

    

    
open func getChildren() -> [SgfNode]  {
    return try!  FfiConverterSequenceTypeSgfNode.lift(try! rustCall() {
    uniffi_qidao_core_fn_method_sgfnode_get_children(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func getId() -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_qidao_core_fn_method_sgfnode_get_id(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func getProperties() -> [SgfProperty]  {
    return try!  FfiConverterSequenceTypeSgfProperty.lift(try! rustCall() {
    uniffi_qidao_core_fn_method_sgfnode_get_properties(
            self.uniffiCloneHandle(),$0
    )
})
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSgfNode: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = SgfNode

    public static func lift(_ handle: UInt64) throws -> SgfNode {
        return SgfNode(unsafeFromHandle: handle)
    }

    public static func lower(_ value: SgfNode) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SgfNode {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: SgfNode, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSgfNode_lift(_ handle: UInt64) throws -> SgfNode {
    return try FfiConverterTypeSgfNode.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSgfNode_lower(_ value: SgfNode) -> UInt64 {
    return FfiConverterTypeSgfNode.lower(value)
}






public protocol SgfTreeProtocol: AnyObject, Sendable {
    
    func root()  -> SgfNode
    
}
open class SgfTree: SgfTreeProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_qidao_core_fn_clone_sgftree(self.handle, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        try! rustCall { uniffi_qidao_core_fn_free_sgftree(handle, $0) }
    }

    

    
open func root() -> SgfNode  {
    return try!  FfiConverterTypeSgfNode_lift(try! rustCall() {
    uniffi_qidao_core_fn_method_sgftree_root(
            self.uniffiCloneHandle(),$0
    )
})
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSgfTree: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = SgfTree

    public static func lift(_ handle: UInt64) throws -> SgfTree {
        return SgfTree(unsafeFromHandle: handle)
    }

    public static func lower(_ value: SgfTree) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SgfTree {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: SgfTree, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSgfTree_lift(_ handle: UInt64) throws -> SgfTree {
    return try FfiConverterTypeSgfTree.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSgfTree_lower(_ value: SgfTree) -> UInt64 {
    return FfiConverterTypeSgfTree.lower(value)
}




public struct AnalysisMoveInfo: Equatable, Hashable {
    public var moveStr: String
    public var visits: UInt32
    public var winrate: Double
    public var scoreLead: Double
    public var pv: [String]

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(moveStr: String, visits: UInt32, winrate: Double, scoreLead: Double, pv: [String]) {
        self.moveStr = moveStr
        self.visits = visits
        self.winrate = winrate
        self.scoreLead = scoreLead
        self.pv = pv
    }

    
}

#if compiler(>=6)
extension AnalysisMoveInfo: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeAnalysisMoveInfo: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> AnalysisMoveInfo {
        return
            try AnalysisMoveInfo(
                moveStr: FfiConverterString.read(from: &buf), 
                visits: FfiConverterUInt32.read(from: &buf), 
                winrate: FfiConverterDouble.read(from: &buf), 
                scoreLead: FfiConverterDouble.read(from: &buf), 
                pv: FfiConverterSequenceString.read(from: &buf)
        )
    }

    public static func write(_ value: AnalysisMoveInfo, into buf: inout [UInt8]) {
        FfiConverterString.write(value.moveStr, into: &buf)
        FfiConverterUInt32.write(value.visits, into: &buf)
        FfiConverterDouble.write(value.winrate, into: &buf)
        FfiConverterDouble.write(value.scoreLead, into: &buf)
        FfiConverterSequenceString.write(value.pv, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAnalysisMoveInfo_lift(_ buf: RustBuffer) throws -> AnalysisMoveInfo {
    return try FfiConverterTypeAnalysisMoveInfo.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAnalysisMoveInfo_lower(_ value: AnalysisMoveInfo) -> RustBuffer {
    return FfiConverterTypeAnalysisMoveInfo.lower(value)
}


public struct AnalysisResult: Equatable, Hashable {
    public var id: String
    public var turnNumber: UInt32
    public var isDuringSearch: Bool
    public var noResults: Bool
    public var rootInfo: AnalysisRootInfo
    public var moveInfos: [AnalysisMoveInfo]
    public var ownership: [Double]?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(id: String, turnNumber: UInt32, isDuringSearch: Bool, noResults: Bool, rootInfo: AnalysisRootInfo, moveInfos: [AnalysisMoveInfo], ownership: [Double]?) {
        self.id = id
        self.turnNumber = turnNumber
        self.isDuringSearch = isDuringSearch
        self.noResults = noResults
        self.rootInfo = rootInfo
        self.moveInfos = moveInfos
        self.ownership = ownership
    }

    
}

#if compiler(>=6)
extension AnalysisResult: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeAnalysisResult: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> AnalysisResult {
        return
            try AnalysisResult(
                id: FfiConverterString.read(from: &buf), 
                turnNumber: FfiConverterUInt32.read(from: &buf), 
                isDuringSearch: FfiConverterBool.read(from: &buf), 
                noResults: FfiConverterBool.read(from: &buf), 
                rootInfo: FfiConverterTypeAnalysisRootInfo.read(from: &buf), 
                moveInfos: FfiConverterSequenceTypeAnalysisMoveInfo.read(from: &buf), 
                ownership: FfiConverterOptionSequenceDouble.read(from: &buf)
        )
    }

    public static func write(_ value: AnalysisResult, into buf: inout [UInt8]) {
        FfiConverterString.write(value.id, into: &buf)
        FfiConverterUInt32.write(value.turnNumber, into: &buf)
        FfiConverterBool.write(value.isDuringSearch, into: &buf)
        FfiConverterBool.write(value.noResults, into: &buf)
        FfiConverterTypeAnalysisRootInfo.write(value.rootInfo, into: &buf)
        FfiConverterSequenceTypeAnalysisMoveInfo.write(value.moveInfos, into: &buf)
        FfiConverterOptionSequenceDouble.write(value.ownership, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAnalysisResult_lift(_ buf: RustBuffer) throws -> AnalysisResult {
    return try FfiConverterTypeAnalysisResult.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAnalysisResult_lower(_ value: AnalysisResult) -> RustBuffer {
    return FfiConverterTypeAnalysisResult.lower(value)
}


public struct AnalysisRootInfo: Equatable, Hashable {
    public var winrate: Double
    public var scoreLead: Double
    public var visits: UInt32

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(winrate: Double, scoreLead: Double, visits: UInt32) {
        self.winrate = winrate
        self.scoreLead = scoreLead
        self.visits = visits
    }

    
}

#if compiler(>=6)
extension AnalysisRootInfo: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeAnalysisRootInfo: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> AnalysisRootInfo {
        return
            try AnalysisRootInfo(
                winrate: FfiConverterDouble.read(from: &buf), 
                scoreLead: FfiConverterDouble.read(from: &buf), 
                visits: FfiConverterUInt32.read(from: &buf)
        )
    }

    public static func write(_ value: AnalysisRootInfo, into buf: inout [UInt8]) {
        FfiConverterDouble.write(value.winrate, into: &buf)
        FfiConverterDouble.write(value.scoreLead, into: &buf)
        FfiConverterUInt32.write(value.visits, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAnalysisRootInfo_lift(_ buf: RustBuffer) throws -> AnalysisRootInfo {
    return try FfiConverterTypeAnalysisRootInfo.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAnalysisRootInfo_lower(_ value: AnalysisRootInfo) -> RustBuffer {
    return FfiConverterTypeAnalysisRootInfo.lower(value)
}


public struct GameMetadata: Equatable, Hashable {
    public var blackName: String
    public var blackRank: String
    public var whiteName: String
    public var whiteRank: String
    public var komi: Double
    public var result: String
    public var date: String
    public var event: String
    public var gameName: String
    public var place: String
    public var size: UInt32

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(blackName: String, blackRank: String, whiteName: String, whiteRank: String, komi: Double, result: String, date: String, event: String, gameName: String, place: String, size: UInt32) {
        self.blackName = blackName
        self.blackRank = blackRank
        self.whiteName = whiteName
        self.whiteRank = whiteRank
        self.komi = komi
        self.result = result
        self.date = date
        self.event = event
        self.gameName = gameName
        self.place = place
        self.size = size
    }

    
}

#if compiler(>=6)
extension GameMetadata: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeGameMetadata: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> GameMetadata {
        return
            try GameMetadata(
                blackName: FfiConverterString.read(from: &buf), 
                blackRank: FfiConverterString.read(from: &buf), 
                whiteName: FfiConverterString.read(from: &buf), 
                whiteRank: FfiConverterString.read(from: &buf), 
                komi: FfiConverterDouble.read(from: &buf), 
                result: FfiConverterString.read(from: &buf), 
                date: FfiConverterString.read(from: &buf), 
                event: FfiConverterString.read(from: &buf), 
                gameName: FfiConverterString.read(from: &buf), 
                place: FfiConverterString.read(from: &buf), 
                size: FfiConverterUInt32.read(from: &buf)
        )
    }

    public static func write(_ value: GameMetadata, into buf: inout [UInt8]) {
        FfiConverterString.write(value.blackName, into: &buf)
        FfiConverterString.write(value.blackRank, into: &buf)
        FfiConverterString.write(value.whiteName, into: &buf)
        FfiConverterString.write(value.whiteRank, into: &buf)
        FfiConverterDouble.write(value.komi, into: &buf)
        FfiConverterString.write(value.result, into: &buf)
        FfiConverterString.write(value.date, into: &buf)
        FfiConverterString.write(value.event, into: &buf)
        FfiConverterString.write(value.gameName, into: &buf)
        FfiConverterString.write(value.place, into: &buf)
        FfiConverterUInt32.write(value.size, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeGameMetadata_lift(_ buf: RustBuffer) throws -> GameMetadata {
    return try FfiConverterTypeGameMetadata.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeGameMetadata_lower(_ value: GameMetadata) -> RustBuffer {
    return FfiConverterTypeGameMetadata.lower(value)
}


public struct GtpResponse: Equatable, Hashable {
    public var success: Bool
    public var text: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(success: Bool, text: String) {
        self.success = success
        self.text = text
    }

    
}

#if compiler(>=6)
extension GtpResponse: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeGtpResponse: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> GtpResponse {
        return
            try GtpResponse(
                success: FfiConverterBool.read(from: &buf), 
                text: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: GtpResponse, into buf: inout [UInt8]) {
        FfiConverterBool.write(value.success, into: &buf)
        FfiConverterString.write(value.text, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeGtpResponse_lift(_ buf: RustBuffer) throws -> GtpResponse {
    return try FfiConverterTypeGtpResponse.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeGtpResponse_lower(_ value: GtpResponse) -> RustBuffer {
    return FfiConverterTypeGtpResponse.lower(value)
}


public struct SgfProperty: Equatable, Hashable {
    public var identifier: String
    public var values: [String]

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(identifier: String, values: [String]) {
        self.identifier = identifier
        self.values = values
    }

    
}

#if compiler(>=6)
extension SgfProperty: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSgfProperty: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SgfProperty {
        return
            try SgfProperty(
                identifier: FfiConverterString.read(from: &buf), 
                values: FfiConverterSequenceString.read(from: &buf)
        )
    }

    public static func write(_ value: SgfProperty, into buf: inout [UInt8]) {
        FfiConverterString.write(value.identifier, into: &buf)
        FfiConverterSequenceString.write(value.values, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSgfProperty_lift(_ buf: RustBuffer) throws -> SgfProperty {
    return try FfiConverterTypeSgfProperty.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSgfProperty_lower(_ value: SgfProperty) -> RustBuffer {
    return FfiConverterTypeSgfProperty.lower(value)
}


public enum SgfError: Swift.Error, Equatable, Hashable, Foundation.LocalizedError {

    
    
    case ParseError(message: String
    )

    

    
    public var errorDescription: String? {
        String(reflecting: self)
    }
    
}

#if compiler(>=6)
extension SgfError: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSgfError: FfiConverterRustBuffer {
    typealias SwiftType = SgfError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SgfError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .ParseError(
            message: try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: SgfError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case let .ParseError(message):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(message, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSgfError_lift(_ buf: RustBuffer) throws -> SgfError {
    return try FfiConverterTypeSgfError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSgfError_lower(_ value: SgfError) -> RustBuffer {
    return FfiConverterTypeSgfError.lower(value)
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum StoneColor: Equatable, Hashable {
    
    case black
    case white



}

#if compiler(>=6)
extension StoneColor: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeStoneColor: FfiConverterRustBuffer {
    typealias SwiftType = StoneColor

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> StoneColor {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .black
        
        case 2: return .white
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: StoneColor, into buf: inout [UInt8]) {
        switch value {
        
        
        case .black:
            writeInt(&buf, Int32(1))
        
        
        case .white:
            writeInt(&buf, Int32(2))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeStoneColor_lift(_ buf: RustBuffer) throws -> StoneColor {
    return try FfiConverterTypeStoneColor.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeStoneColor_lower(_ value: StoneColor) -> RustBuffer {
    return FfiConverterTypeStoneColor.lower(value)
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeSgfProperty: FfiConverterRustBuffer {
    typealias SwiftType = SgfProperty?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeSgfProperty.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeSgfProperty.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeStoneColor: FfiConverterRustBuffer {
    typealias SwiftType = StoneColor?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeStoneColor.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeStoneColor.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionSequenceDouble: FfiConverterRustBuffer {
    typealias SwiftType = [Double]?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterSequenceDouble.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterSequenceDouble.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceDouble: FfiConverterRustBuffer {
    typealias SwiftType = [Double]

    public static func write(_ value: [Double], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterDouble.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [Double] {
        let len: Int32 = try readInt(&buf)
        var seq = [Double]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterDouble.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]

    public static func write(_ value: [String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterString.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String] {
        let len: Int32 = try readInt(&buf)
        var seq = [String]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterString.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeSgfNode: FfiConverterRustBuffer {
    typealias SwiftType = [SgfNode]

    public static func write(_ value: [SgfNode], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeSgfNode.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [SgfNode] {
        let len: Int32 = try readInt(&buf)
        var seq = [SgfNode]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeSgfNode.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeAnalysisMoveInfo: FfiConverterRustBuffer {
    typealias SwiftType = [AnalysisMoveInfo]

    public static func write(_ value: [AnalysisMoveInfo], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeAnalysisMoveInfo.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [AnalysisMoveInfo] {
        let len: Int32 = try readInt(&buf)
        var seq = [AnalysisMoveInfo]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeAnalysisMoveInfo.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeSgfProperty: FfiConverterRustBuffer {
    typealias SwiftType = [SgfProperty]

    public static func write(_ value: [SgfProperty], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeSgfProperty.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [SgfProperty] {
        let len: Int32 = try readInt(&buf)
        var seq = [SgfProperty]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeSgfProperty.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [[String]]

    public static func write(_ value: [[String]], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterSequenceString.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [[String]] {
        let len: Int32 = try readInt(&buf)
        var seq = [[String]]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterSequenceString.read(from: &buf))
        }
        return seq
    }
}
private let UNIFFI_RUST_FUTURE_POLL_READY: Int8 = 0
private let UNIFFI_RUST_FUTURE_POLL_WAKE: Int8 = 1

fileprivate let uniffiContinuationHandleMap = UniffiHandleMap<UnsafeContinuation<Int8, Never>>()

fileprivate func uniffiRustCallAsync<F, T>(
    rustFutureFunc: () -> UInt64,
    pollFunc: (UInt64, @escaping UniffiRustFutureContinuationCallback, UInt64) -> (),
    completeFunc: (UInt64, UnsafeMutablePointer<RustCallStatus>) -> F,
    freeFunc: (UInt64) -> (),
    liftFunc: (F) throws -> T,
    errorHandler: ((RustBuffer) throws -> Swift.Error)?
) async throws -> T {
    // Make sure to call the ensure init function since future creation doesn't have a
    // RustCallStatus param, so doesn't use makeRustCall()
    uniffiEnsureQidaoCoreInitialized()
    let rustFuture = rustFutureFunc()
    defer {
        freeFunc(rustFuture)
    }
    var pollResult: Int8;
    repeat {
        pollResult = await withUnsafeContinuation {
            pollFunc(
                rustFuture,
                { handle, pollResult in
                    uniffiFutureContinuationCallback(handle: handle, pollResult: pollResult)
                },
                uniffiContinuationHandleMap.insert(obj: $0)
            )
        }
    } while pollResult != UNIFFI_RUST_FUTURE_POLL_READY

    return try liftFunc(makeRustCall(
        { completeFunc(rustFuture, $0) },
        errorHandler: errorHandler
    ))
}

// Callback handlers for an async calls.  These are invoked by Rust when the future is ready.  They
// lift the return value or error and resume the suspended function.
fileprivate func uniffiFutureContinuationCallback(handle: UInt64, pollResult: Int8) {
    if let continuation = try? uniffiContinuationHandleMap.remove(handle: handle) {
        continuation.resume(returning: pollResult)
    } else {
        print("uniffiFutureContinuationCallback invalid handle")
    }
}
public func add(a: UInt32, b: UInt32) -> UInt32  {
    return try!  FfiConverterUInt32.lift(try! rustCall() {
    uniffi_qidao_core_fn_func_add(
        FfiConverterUInt32.lower(a),
        FfiConverterUInt32.lower(b),$0
    )
})
}
public func parseSgf(sgfContent: String)throws  -> SgfTree  {
    return try  FfiConverterTypeSgfTree_lift(try rustCallWithError(FfiConverterTypeSgfError_lift) {
    uniffi_qidao_core_fn_func_parse_sgf(
        FfiConverterString.lower(sgfContent),$0
    )
})
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 30
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_qidao_core_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_qidao_core_checksum_func_add() != 3207) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_qidao_core_checksum_func_parse_sgf() != 27662) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_qidao_core_checksum_method_analysisengine_add_internal_log() != 36426) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_qidao_core_checksum_method_analysisengine_analyze() != 52960) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_qidao_core_checksum_method_analysisengine_get_logs() != 39263) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_qidao_core_checksum_method_analysisengine_get_next_result() != 38822) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_qidao_core_checksum_method_analysisengine_set_logging_enabled() != 20868) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_qidao_core_checksum_method_analysisengine_start() != 33656) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_qidao_core_checksum_method_analysisengine_stop() != 64484) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_qidao_core_checksum_method_analysisengine_terminate() != 48581) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_qidao_core_checksum_method_analysisengine_terminate_all() != 19481) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_qidao_core_checksum_method_board_get_size() != 42284) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_qidao_core_checksum_method_board_get_stone() != 54210) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_qidao_core_checksum_method_board_place_stone() != 53205) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_qidao_core_checksum_method_board_with_stone() != 42743) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_qidao_core_checksum_method_game_can_go_back() != 61635) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_qidao_core_checksum_method_game_can_go_forward() != 40449) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_qidao_core_checksum_method_game_get_analysis_moves() != 24472) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_qidao_core_checksum_method_game_get_board() != 38261) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_qidao_core_checksum_method_game_get_current_board_stones() != 43448) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_qidao_core_checksum_method_game_get_current_node() != 11635) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_qidao_core_checksum_method_game_get_current_path_moves() != 52188) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_qidao_core_checksum_method_game_get_current_variation_index() != 3639) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_qidao_core_checksum_method_game_get_initial_stones() != 28328) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_qidao_core_checksum_method_game_get_last_move() != 39187) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_qidao_core_checksum_method_game_get_main_line_moves() != 36304) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_qidao_core_checksum_method_game_get_max_move_count() != 20201) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_qidao_core_checksum_method_game_get_metadata() != 39160) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_qidao_core_checksum_method_game_get_move_count() != 34766) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_qidao_core_checksum_method_game_get_next_color() != 59788) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_qidao_core_checksum_method_game_get_root_node() != 23784) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_qidao_core_checksum_method_game_get_variation_count() != 32672) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_qidao_core_checksum_method_game_go_back() != 63939) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_qidao_core_checksum_method_game_go_forward() != 27437) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_qidao_core_checksum_method_game_jump_to_move_number() != 51090) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_qidao_core_checksum_method_game_jump_to_node() != 53846) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_qidao_core_checksum_method_game_place_stone() != 19675) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_qidao_core_checksum_method_game_set_metadata() != 11810) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_qidao_core_checksum_method_game_to_sgf() != 50649) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_qidao_core_checksum_method_gtpengine_send_command() != 5407) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_qidao_core_checksum_method_gtpengine_start() != 18533) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_qidao_core_checksum_method_gtpengine_stop() != 50356) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_qidao_core_checksum_method_sgfnode_get_children() != 34594) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_qidao_core_checksum_method_sgfnode_get_id() != 55131) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_qidao_core_checksum_method_sgfnode_get_properties() != 16786) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_qidao_core_checksum_method_sgftree_root() != 50046) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_qidao_core_checksum_constructor_analysisengine_new() != 18407) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_qidao_core_checksum_constructor_board_new() != 44876) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_qidao_core_checksum_constructor_game_from_sgf() != 52989) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_qidao_core_checksum_constructor_game_new() != 12242) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_qidao_core_checksum_constructor_gtpengine_new() != 56626) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureQidaoCoreInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all