// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(qidao_coreFFI)
import qidao_coreFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_qidao_core_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_qidao_core_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
fileprivate class UniffiHandleMap<T> {
    private var map: [UInt64: T] = [:]
    private let lock = NSLock()
    private var currentHandle: UInt64 = 1

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            let handle = currentHandle
            currentHandle += 1
            map[handle] = obj
            return handle
        }
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterDouble: FfiConverterPrimitive {
    typealias FfiType = Double
    typealias SwiftType = Double

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Double {
        return try lift(readDouble(&buf))
    }

    public static func write(_ value: Double, into buf: inout [UInt8]) {
        writeDouble(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}




public protocol BoardProtocol : AnyObject {
    
    func getSize()  -> UInt32
    
    func getStone(x: UInt32, y: UInt32)  -> StoneColor?
    
    /**
     * Attempts to place a stone. Returns true if successful.
     */
    func placeStone(x: UInt32, y: UInt32, color: StoneColor) throws  -> Board
    
}

open class Board:
    BoardProtocol {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_qidao_core_fn_clone_board(self.pointer, $0) }
    }
public convenience init(size: UInt32) {
    let pointer =
        try! rustCall() {
    uniffi_qidao_core_fn_constructor_board_new(
        FfiConverterUInt32.lower(size),$0
    )
}
    self.init(unsafeFromRawPointer: pointer)
}

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_qidao_core_fn_free_board(pointer, $0) }
    }

    

    
open func getSize() -> UInt32 {
    return try!  FfiConverterUInt32.lift(try! rustCall() {
    uniffi_qidao_core_fn_method_board_get_size(self.uniffiClonePointer(),$0
    )
})
}
    
open func getStone(x: UInt32, y: UInt32) -> StoneColor? {
    return try!  FfiConverterOptionTypeStoneColor.lift(try! rustCall() {
    uniffi_qidao_core_fn_method_board_get_stone(self.uniffiClonePointer(),
        FfiConverterUInt32.lower(x),
        FfiConverterUInt32.lower(y),$0
    )
})
}
    
    /**
     * Attempts to place a stone. Returns true if successful.
     */
open func placeStone(x: UInt32, y: UInt32, color: StoneColor)throws  -> Board {
    return try  FfiConverterTypeBoard.lift(try rustCallWithError(FfiConverterTypeSgfError.lift) {
    uniffi_qidao_core_fn_method_board_place_stone(self.uniffiClonePointer(),
        FfiConverterUInt32.lower(x),
        FfiConverterUInt32.lower(y),
        FfiConverterTypeStoneColor.lower(color),$0
    )
})
}
    

}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeBoard: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = Board

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> Board {
        return Board(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: Board) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Board {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: Board, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}




#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeBoard_lift(_ pointer: UnsafeMutableRawPointer) throws -> Board {
    return try FfiConverterTypeBoard.lift(pointer)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeBoard_lower(_ value: Board) -> UnsafeMutableRawPointer {
    return FfiConverterTypeBoard.lower(value)
}




public protocol GameProtocol : AnyObject {
    
    func canGoBack()  -> Bool
    
    func canGoForward()  -> Bool
    
    func getBoard()  -> Board
    
    func getCurrentNode()  -> SgfNode
    
    func getCurrentPathMoves()  -> [SgfProperty]
    
    func getCurrentVariationIndex()  -> UInt32
    
    func getLastMove()  -> SgfProperty?
    
    func getMetadata()  -> GameMetadata
    
    func getMoveCount()  -> UInt32
    
    func getNextColor()  -> StoneColor
    
    func getRootNode()  -> SgfNode
    
    func getVariationCount()  -> UInt32
    
    func goBack()  -> Bool
    
    func goForward(index: UInt32)  -> Bool
    
    func jumpToNode(target: SgfNode) 
    
    func placeStone(x: UInt32, y: UInt32, color: StoneColor) throws 
    
    func setMetadata(metadata: GameMetadata) 
    
    func toSgf()  -> String
    
}

open class Game:
    GameProtocol {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_qidao_core_fn_clone_game(self.pointer, $0) }
    }
public convenience init(size: UInt32) {
    let pointer =
        try! rustCall() {
    uniffi_qidao_core_fn_constructor_game_new(
        FfiConverterUInt32.lower(size),$0
    )
}
    self.init(unsafeFromRawPointer: pointer)
}

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_qidao_core_fn_free_game(pointer, $0) }
    }

    
public static func fromSgf(sgfContent: String)throws  -> Game {
    return try  FfiConverterTypeGame.lift(try rustCallWithError(FfiConverterTypeSgfError.lift) {
    uniffi_qidao_core_fn_constructor_game_from_sgf(
        FfiConverterString.lower(sgfContent),$0
    )
})
}
    

    
open func canGoBack() -> Bool {
    return try!  FfiConverterBool.lift(try! rustCall() {
    uniffi_qidao_core_fn_method_game_can_go_back(self.uniffiClonePointer(),$0
    )
})
}
    
open func canGoForward() -> Bool {
    return try!  FfiConverterBool.lift(try! rustCall() {
    uniffi_qidao_core_fn_method_game_can_go_forward(self.uniffiClonePointer(),$0
    )
})
}
    
open func getBoard() -> Board {
    return try!  FfiConverterTypeBoard.lift(try! rustCall() {
    uniffi_qidao_core_fn_method_game_get_board(self.uniffiClonePointer(),$0
    )
})
}
    
open func getCurrentNode() -> SgfNode {
    return try!  FfiConverterTypeSgfNode.lift(try! rustCall() {
    uniffi_qidao_core_fn_method_game_get_current_node(self.uniffiClonePointer(),$0
    )
})
}
    
open func getCurrentPathMoves() -> [SgfProperty] {
    return try!  FfiConverterSequenceTypeSgfProperty.lift(try! rustCall() {
    uniffi_qidao_core_fn_method_game_get_current_path_moves(self.uniffiClonePointer(),$0
    )
})
}
    
open func getCurrentVariationIndex() -> UInt32 {
    return try!  FfiConverterUInt32.lift(try! rustCall() {
    uniffi_qidao_core_fn_method_game_get_current_variation_index(self.uniffiClonePointer(),$0
    )
})
}
    
open func getLastMove() -> SgfProperty? {
    return try!  FfiConverterOptionTypeSgfProperty.lift(try! rustCall() {
    uniffi_qidao_core_fn_method_game_get_last_move(self.uniffiClonePointer(),$0
    )
})
}
    
open func getMetadata() -> GameMetadata {
    return try!  FfiConverterTypeGameMetadata.lift(try! rustCall() {
    uniffi_qidao_core_fn_method_game_get_metadata(self.uniffiClonePointer(),$0
    )
})
}
    
open func getMoveCount() -> UInt32 {
    return try!  FfiConverterUInt32.lift(try! rustCall() {
    uniffi_qidao_core_fn_method_game_get_move_count(self.uniffiClonePointer(),$0
    )
})
}
    
open func getNextColor() -> StoneColor {
    return try!  FfiConverterTypeStoneColor.lift(try! rustCall() {
    uniffi_qidao_core_fn_method_game_get_next_color(self.uniffiClonePointer(),$0
    )
})
}
    
open func getRootNode() -> SgfNode {
    return try!  FfiConverterTypeSgfNode.lift(try! rustCall() {
    uniffi_qidao_core_fn_method_game_get_root_node(self.uniffiClonePointer(),$0
    )
})
}
    
open func getVariationCount() -> UInt32 {
    return try!  FfiConverterUInt32.lift(try! rustCall() {
    uniffi_qidao_core_fn_method_game_get_variation_count(self.uniffiClonePointer(),$0
    )
})
}
    
open func goBack() -> Bool {
    return try!  FfiConverterBool.lift(try! rustCall() {
    uniffi_qidao_core_fn_method_game_go_back(self.uniffiClonePointer(),$0
    )
})
}
    
open func goForward(index: UInt32) -> Bool {
    return try!  FfiConverterBool.lift(try! rustCall() {
    uniffi_qidao_core_fn_method_game_go_forward(self.uniffiClonePointer(),
        FfiConverterUInt32.lower(index),$0
    )
})
}
    
open func jumpToNode(target: SgfNode) {try! rustCall() {
    uniffi_qidao_core_fn_method_game_jump_to_node(self.uniffiClonePointer(),
        FfiConverterTypeSgfNode.lower(target),$0
    )
}
}
    
open func placeStone(x: UInt32, y: UInt32, color: StoneColor)throws  {try rustCallWithError(FfiConverterTypeSgfError.lift) {
    uniffi_qidao_core_fn_method_game_place_stone(self.uniffiClonePointer(),
        FfiConverterUInt32.lower(x),
        FfiConverterUInt32.lower(y),
        FfiConverterTypeStoneColor.lower(color),$0
    )
}
}
    
open func setMetadata(metadata: GameMetadata) {try! rustCall() {
    uniffi_qidao_core_fn_method_game_set_metadata(self.uniffiClonePointer(),
        FfiConverterTypeGameMetadata.lower(metadata),$0
    )
}
}
    
open func toSgf() -> String {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_qidao_core_fn_method_game_to_sgf(self.uniffiClonePointer(),$0
    )
})
}
    

}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeGame: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = Game

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> Game {
        return Game(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: Game) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Game {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: Game, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}




#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeGame_lift(_ pointer: UnsafeMutableRawPointer) throws -> Game {
    return try FfiConverterTypeGame.lift(pointer)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeGame_lower(_ value: Game) -> UnsafeMutableRawPointer {
    return FfiConverterTypeGame.lower(value)
}




public protocol SgfNodeProtocol : AnyObject {
    
    func getChildren()  -> [SgfNode]
    
    func getId()  -> String
    
    func getProperties()  -> [SgfProperty]
    
}

open class SgfNode:
    SgfNodeProtocol {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_qidao_core_fn_clone_sgfnode(self.pointer, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_qidao_core_fn_free_sgfnode(pointer, $0) }
    }

    

    
open func getChildren() -> [SgfNode] {
    return try!  FfiConverterSequenceTypeSgfNode.lift(try! rustCall() {
    uniffi_qidao_core_fn_method_sgfnode_get_children(self.uniffiClonePointer(),$0
    )
})
}
    
open func getId() -> String {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_qidao_core_fn_method_sgfnode_get_id(self.uniffiClonePointer(),$0
    )
})
}
    
open func getProperties() -> [SgfProperty] {
    return try!  FfiConverterSequenceTypeSgfProperty.lift(try! rustCall() {
    uniffi_qidao_core_fn_method_sgfnode_get_properties(self.uniffiClonePointer(),$0
    )
})
}
    

}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSgfNode: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = SgfNode

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> SgfNode {
        return SgfNode(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: SgfNode) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SgfNode {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: SgfNode, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}




#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSgfNode_lift(_ pointer: UnsafeMutableRawPointer) throws -> SgfNode {
    return try FfiConverterTypeSgfNode.lift(pointer)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSgfNode_lower(_ value: SgfNode) -> UnsafeMutableRawPointer {
    return FfiConverterTypeSgfNode.lower(value)
}




public protocol SgfTreeProtocol : AnyObject {
    
    func root()  -> SgfNode
    
}

open class SgfTree:
    SgfTreeProtocol {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_qidao_core_fn_clone_sgftree(self.pointer, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_qidao_core_fn_free_sgftree(pointer, $0) }
    }

    

    
open func root() -> SgfNode {
    return try!  FfiConverterTypeSgfNode.lift(try! rustCall() {
    uniffi_qidao_core_fn_method_sgftree_root(self.uniffiClonePointer(),$0
    )
})
}
    

}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSgfTree: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = SgfTree

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> SgfTree {
        return SgfTree(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: SgfTree) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SgfTree {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: SgfTree, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}




#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSgfTree_lift(_ pointer: UnsafeMutableRawPointer) throws -> SgfTree {
    return try FfiConverterTypeSgfTree.lift(pointer)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSgfTree_lower(_ value: SgfTree) -> UnsafeMutableRawPointer {
    return FfiConverterTypeSgfTree.lower(value)
}


public struct GameMetadata {
    public var blackName: String
    public var blackRank: String
    public var whiteName: String
    public var whiteRank: String
    public var komi: Double
    public var result: String
    public var date: String
    public var event: String
    public var gameName: String
    public var place: String
    public var size: UInt32

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(blackName: String, blackRank: String, whiteName: String, whiteRank: String, komi: Double, result: String, date: String, event: String, gameName: String, place: String, size: UInt32) {
        self.blackName = blackName
        self.blackRank = blackRank
        self.whiteName = whiteName
        self.whiteRank = whiteRank
        self.komi = komi
        self.result = result
        self.date = date
        self.event = event
        self.gameName = gameName
        self.place = place
        self.size = size
    }
}



extension GameMetadata: Equatable, Hashable {
    public static func ==(lhs: GameMetadata, rhs: GameMetadata) -> Bool {
        if lhs.blackName != rhs.blackName {
            return false
        }
        if lhs.blackRank != rhs.blackRank {
            return false
        }
        if lhs.whiteName != rhs.whiteName {
            return false
        }
        if lhs.whiteRank != rhs.whiteRank {
            return false
        }
        if lhs.komi != rhs.komi {
            return false
        }
        if lhs.result != rhs.result {
            return false
        }
        if lhs.date != rhs.date {
            return false
        }
        if lhs.event != rhs.event {
            return false
        }
        if lhs.gameName != rhs.gameName {
            return false
        }
        if lhs.place != rhs.place {
            return false
        }
        if lhs.size != rhs.size {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(blackName)
        hasher.combine(blackRank)
        hasher.combine(whiteName)
        hasher.combine(whiteRank)
        hasher.combine(komi)
        hasher.combine(result)
        hasher.combine(date)
        hasher.combine(event)
        hasher.combine(gameName)
        hasher.combine(place)
        hasher.combine(size)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeGameMetadata: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> GameMetadata {
        return
            try GameMetadata(
                blackName: FfiConverterString.read(from: &buf), 
                blackRank: FfiConverterString.read(from: &buf), 
                whiteName: FfiConverterString.read(from: &buf), 
                whiteRank: FfiConverterString.read(from: &buf), 
                komi: FfiConverterDouble.read(from: &buf), 
                result: FfiConverterString.read(from: &buf), 
                date: FfiConverterString.read(from: &buf), 
                event: FfiConverterString.read(from: &buf), 
                gameName: FfiConverterString.read(from: &buf), 
                place: FfiConverterString.read(from: &buf), 
                size: FfiConverterUInt32.read(from: &buf)
        )
    }

    public static func write(_ value: GameMetadata, into buf: inout [UInt8]) {
        FfiConverterString.write(value.blackName, into: &buf)
        FfiConverterString.write(value.blackRank, into: &buf)
        FfiConverterString.write(value.whiteName, into: &buf)
        FfiConverterString.write(value.whiteRank, into: &buf)
        FfiConverterDouble.write(value.komi, into: &buf)
        FfiConverterString.write(value.result, into: &buf)
        FfiConverterString.write(value.date, into: &buf)
        FfiConverterString.write(value.event, into: &buf)
        FfiConverterString.write(value.gameName, into: &buf)
        FfiConverterString.write(value.place, into: &buf)
        FfiConverterUInt32.write(value.size, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeGameMetadata_lift(_ buf: RustBuffer) throws -> GameMetadata {
    return try FfiConverterTypeGameMetadata.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeGameMetadata_lower(_ value: GameMetadata) -> RustBuffer {
    return FfiConverterTypeGameMetadata.lower(value)
}


public struct SgfProperty {
    public var identifier: String
    public var values: [String]

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(identifier: String, values: [String]) {
        self.identifier = identifier
        self.values = values
    }
}



extension SgfProperty: Equatable, Hashable {
    public static func ==(lhs: SgfProperty, rhs: SgfProperty) -> Bool {
        if lhs.identifier != rhs.identifier {
            return false
        }
        if lhs.values != rhs.values {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(identifier)
        hasher.combine(values)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSgfProperty: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SgfProperty {
        return
            try SgfProperty(
                identifier: FfiConverterString.read(from: &buf), 
                values: FfiConverterSequenceString.read(from: &buf)
        )
    }

    public static func write(_ value: SgfProperty, into buf: inout [UInt8]) {
        FfiConverterString.write(value.identifier, into: &buf)
        FfiConverterSequenceString.write(value.values, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSgfProperty_lift(_ buf: RustBuffer) throws -> SgfProperty {
    return try FfiConverterTypeSgfProperty.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSgfProperty_lower(_ value: SgfProperty) -> RustBuffer {
    return FfiConverterTypeSgfProperty.lower(value)
}


public enum SgfError {

    
    
    case ParseError(message: String
    )
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSgfError: FfiConverterRustBuffer {
    typealias SwiftType = SgfError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SgfError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .ParseError(
            message: try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: SgfError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case let .ParseError(message):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(message, into: &buf)
            
        }
    }
}


extension SgfError: Equatable, Hashable {}

extension SgfError: Foundation.LocalizedError {
    public var errorDescription: String? {
        String(reflecting: self)
    }
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum StoneColor {
    
    case black
    case white
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeStoneColor: FfiConverterRustBuffer {
    typealias SwiftType = StoneColor

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> StoneColor {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .black
        
        case 2: return .white
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: StoneColor, into buf: inout [UInt8]) {
        switch value {
        
        
        case .black:
            writeInt(&buf, Int32(1))
        
        
        case .white:
            writeInt(&buf, Int32(2))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeStoneColor_lift(_ buf: RustBuffer) throws -> StoneColor {
    return try FfiConverterTypeStoneColor.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeStoneColor_lower(_ value: StoneColor) -> RustBuffer {
    return FfiConverterTypeStoneColor.lower(value)
}



extension StoneColor: Equatable, Hashable {}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeSgfProperty: FfiConverterRustBuffer {
    typealias SwiftType = SgfProperty?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeSgfProperty.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeSgfProperty.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeStoneColor: FfiConverterRustBuffer {
    typealias SwiftType = StoneColor?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeStoneColor.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeStoneColor.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]

    public static func write(_ value: [String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterString.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String] {
        let len: Int32 = try readInt(&buf)
        var seq = [String]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterString.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeSgfNode: FfiConverterRustBuffer {
    typealias SwiftType = [SgfNode]

    public static func write(_ value: [SgfNode], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeSgfNode.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [SgfNode] {
        let len: Int32 = try readInt(&buf)
        var seq = [SgfNode]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeSgfNode.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeSgfProperty: FfiConverterRustBuffer {
    typealias SwiftType = [SgfProperty]

    public static func write(_ value: [SgfProperty], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeSgfProperty.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [SgfProperty] {
        let len: Int32 = try readInt(&buf)
        var seq = [SgfProperty]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeSgfProperty.read(from: &buf))
        }
        return seq
    }
}
public func add(a: UInt32, b: UInt32) -> UInt32 {
    return try!  FfiConverterUInt32.lift(try! rustCall() {
    uniffi_qidao_core_fn_func_add(
        FfiConverterUInt32.lower(a),
        FfiConverterUInt32.lower(b),$0
    )
})
}
public func parseSgf(sgfContent: String)throws  -> SgfTree {
    return try  FfiConverterTypeSgfTree.lift(try rustCallWithError(FfiConverterTypeSgfError.lift) {
    uniffi_qidao_core_fn_func_parse_sgf(
        FfiConverterString.lower(sgfContent),$0
    )
})
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private var initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 26
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_qidao_core_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_qidao_core_checksum_func_add() != 3207) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_qidao_core_checksum_func_parse_sgf() != 27662) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_qidao_core_checksum_method_board_get_size() != 42284) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_qidao_core_checksum_method_board_get_stone() != 54210) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_qidao_core_checksum_method_board_place_stone() != 53205) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_qidao_core_checksum_method_game_can_go_back() != 61635) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_qidao_core_checksum_method_game_can_go_forward() != 40449) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_qidao_core_checksum_method_game_get_board() != 38261) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_qidao_core_checksum_method_game_get_current_node() != 11635) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_qidao_core_checksum_method_game_get_current_path_moves() != 52188) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_qidao_core_checksum_method_game_get_current_variation_index() != 3639) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_qidao_core_checksum_method_game_get_last_move() != 39187) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_qidao_core_checksum_method_game_get_metadata() != 39160) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_qidao_core_checksum_method_game_get_move_count() != 34766) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_qidao_core_checksum_method_game_get_next_color() != 59788) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_qidao_core_checksum_method_game_get_root_node() != 23784) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_qidao_core_checksum_method_game_get_variation_count() != 32672) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_qidao_core_checksum_method_game_go_back() != 63939) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_qidao_core_checksum_method_game_go_forward() != 27437) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_qidao_core_checksum_method_game_jump_to_node() != 53846) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_qidao_core_checksum_method_game_place_stone() != 19675) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_qidao_core_checksum_method_game_set_metadata() != 11810) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_qidao_core_checksum_method_game_to_sgf() != 50649) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_qidao_core_checksum_method_sgfnode_get_children() != 34594) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_qidao_core_checksum_method_sgfnode_get_id() != 55131) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_qidao_core_checksum_method_sgfnode_get_properties() != 16786) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_qidao_core_checksum_method_sgftree_root() != 50046) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_qidao_core_checksum_constructor_board_new() != 44876) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_qidao_core_checksum_constructor_game_from_sgf() != 52989) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_qidao_core_checksum_constructor_game_new() != 12242) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

private func uniffiEnsureInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all